def format_retrieved_guidance(retrieved_docs):
    lines = []
    for i, doc in enumerate(retrieved_docs, start=1):
        source = doc["source"]
        text_preview = " ".join(doc["text"].replace("\n", " ").split())
        if len(text_preview) > 500:
            text_preview = text_preview[:500] + "..."
        lines.append(f"[{i}] Source: {source}\n{text_preview}")
    return "\n\n".join(lines)


def generate_rag_enriched_report(risk_level, risk_score, shap_reasons, retrieved_docs, recommendation):
    shap_text = "\n".join([f"- {reason}" for reason in shap_reasons])
    guidance_text = format_retrieved_guidance(retrieved_docs)
    return f"""AML Analyst Report

Risk Level: {risk_level}
Risk Score: {risk_score * 100:.2f} / 100

Model Findings:
The transaction was assessed using an XGBoost-based AML risk model. The most important model explanation factors were:

{shap_text}

Retrieved AML Guidance:
The following AML guidance was retrieved from the local knowledge base:

{guidance_text}

Analyst Assessment:
The model output and retrieved guidance should be reviewed together. The listed risk drivers may indicate suspicious activity patterns such as structuring, layering, unusual transaction timing, cross-currency movement, cross-border exposure, or unclear transaction purpose depending on the full customer context.

Recommendation:
{recommendation}

Important Note:
This report is generated by a prototype AI system for portfolio demonstration. It does not replace human compliance review and is not a production AML decisioning system.
"""
